# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-14 11:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0015_auto_20190131_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('cadastro', models.DateTimeField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_do_cliente', to='clientes.Cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_do_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('cadastro',),
                'verbose_name': 'Invent\xe1rio',
                'verbose_name_plural': 'Invent\xe1rios',
            },
        ),
    ]
