# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
