# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-14 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_inventarioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
