# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-19 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_inventarioitem_contado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='inicio',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tempo',
            field=models.IntegerField(default=0),
        ),
    ]
