# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0027_auto_20190212_1431'),
        ('inventario', '0007_auto_20190218_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_sistema', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoqueinventario_do_inventario', to='inventario.Inventario')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoqueinventario_do_produto', to='produtos.Produto')),
            ],
            options={
                'ordering': ('produto',),
                'verbose_name': 'Estoque Invent\xe1rio',
                'verbose_name_plural': 'Estoque Invent\xe1rio',
            },
        ),
    ]
