# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-21 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_inventarioitem_produto_custo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueinventario',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='estoqueinventario',
            name='produto_custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
