# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20190221_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='importacao_estoque_sistema',
            field=models.BooleanField(default=True, help_text='Fica "verdadeiro" quando finaliza o processo de importa\xe7\xe3o dos dados para a base.', verbose_name='Importa\xe7\xe3o Estoque Sistema'),
        ),
    ]
