# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-27 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_inventario_importacao_estoque_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='upload_arquivo_estoque_sistema',
            field=models.BooleanField(default=False, help_text='Fica "verdadeiro" quando foi feito o upload de arquivo para ser processado na base.', verbose_name='Upload Arquivo Estoque Sistema'),
        ),
    ]
