# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_inventario_erros_importacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='opcao_duplicados',
            field=models.CharField(choices=[(b'1', 'Ignorar os produtos duplicados'), (b'2', 'Somar quantidade dos produtos duplicados'), (b'3', 'Substituir os produtos duplicados')], default='1', help_text='O que o sistema deve fazer quando encontrar um produto que j\xe1 foi importado: "Ignorar", "Somar" ou "Substituir"?', max_length=1, verbose_name='Op\xe7\xe3o produtos duplicados'),
        ),
    ]
