# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-10 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_inventarioitem_gondola_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gondolainventario',
            name='fechamento',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
