# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-17 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20190410_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='gondolainventario',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
