# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_gondolainventario_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
