# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_inventario_quantidade_distintos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioitem',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=12, null=True),
        ),
    ]
