# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_auto_20190425_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gondolainventario',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=12, null=True),
        ),
    ]
