# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-05-09 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_auto_20190426_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ('cadastro',), 'permissions': (('abre_acompanhamento_gondolas', 'Abre Acompanhamento G\xf4ndolas'),), 'verbose_name': 'Invent\xe1rio', 'verbose_name_plural': 'Invent\xe1rios'},
        ),
    ]
