# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-08-20 15:28
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0039_auto_20190805_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='secoes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'g', 'Geral'), (b's', 'Se\xe7\xe3o')], default='g', max_length=3, null=True),
        ),
    ]
