# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-08-20 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_funcionariofuncao_cliente'),
        ('inventario', '0040_inventario_secoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Se\xe7\xe3o / Invent\xe1rio',
                'verbose_name_plural': 'Se\xe7\xf5es / Invent\xe1rios',
            },
        ),
        migrations.AlterField(
            model_name='inventario',
            name='secao',
            field=models.ForeignKey(blank=True, help_text='Escolha a se\xe7\xe3o do invent\xe1rio. Caso n\xe3o escolha nenhuma, o invent\xe1rio ser\xe1 Geral', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_da_secao', to='clientes.Secao'),
        ),
        migrations.AddField(
            model_name='secaoinventario',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Inventario'),
        ),
        migrations.AddField(
            model_name='secaoinventario',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Secao'),
        ),
    ]
