# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-08-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0041_auto_20190820_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='secao',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='secoes',
        ),
    ]
