# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-08-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0042_auto_20190820_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='secoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
