# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-21 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='custo_total',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='embalagem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_fisico_deposito',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_fisico_gondola',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_fisico_total',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_sistema',
        ),
    ]
