# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20190121_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_interno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together=set([('cliente', 'codigo_interno')]),
        ),
    ]
