# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-22 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20190121_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('estoque_fisico_gondola', models.IntegerField(blank=True, default=0, null=True)),
                ('estoque_fisico_deposito', models.IntegerField(blank=True, default=0, null=True)),
                ('estoque_fisico_total', models.IntegerField(blank=True, default=0, null=True)),
                ('estoque_sistema', models.IntegerField(blank=True, default=0, null=True)),
                ('embalagem', models.IntegerField(blank=True, default=0, null=True)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('dia', models.CharField(blank=True, max_length=2, null=True)),
                ('mes', models.CharField(blank=True, choices=[(b'1', 'Janeiro'), (b'2', 'Fevereiro'), (b'3', 'Mar\xe7o'), (b'4', 'Abril'), (b'5', 'Maio'), (b'6', 'Junho'), (b'7', 'Julho'), (b'8', 'Agosto'), (b'9', 'Setembro'), (b'10', 'Outubro'), (b'11', 'Novembro'), (b'12', 'Dezembro')], max_length=2, null=True)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('semana', models.CharField(blank=True, max_length=2, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_do_produto', to='produtos.Produto')),
            ],
            options={
                'ordering': ('produto',),
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoque',
            },
        ),
    ]
