# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_estoquediario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquediario',
            name='diferenca',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
