# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20190122_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquediario',
            name='estoque_fisico_avaria',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='estoquediario',
            name='estoque_fisico_lanche',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='estoquediario',
            name='estoque_fisico_outros',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='estoquediario',
            name='estoque_fisico_producao',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
