# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-24 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20190122_0843'),
        ('produtos', '0009_auto_20190124_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.IntegerField(db_index=True, default=0)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_do_cliente', to='clientes.Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_do_produto', to='produtos.Produto')),
            ],
            options={
                'verbose_name': 'Cliente Produto',
                'verbose_name_plural': 'Clientes Produtos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='clienteproduto',
            unique_together=set([('cliente', 'produto')]),
        ),
    ]
