# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-24 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_auto_20190124_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquediario',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoque'},
        ),
        migrations.RemoveField(
            model_name='estoquediario',
            name='produto',
        ),
    ]
