# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-24 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_auto_20190124_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquediario',
            name='cliente_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoques_do_produto', to='produtos.ClienteProduto'),
        ),
    ]
