# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-07 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_auto_20190205_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('descricao',), 'permissions': (('importar_planilha', 'Pode Importar Planilha Excel'), ('gerar_pdf_contagem_totativo', 'Gerar PDF Contagem Estoque Rotativo'), ('gerar_pdf_analitico_contagem_totativo', 'Gerar PDF Anal\xedtico Contagem Estoque Rotativo'), ('adicionar_estoque_manualmente', 'Pode Adicionar Estoque Manualmente'), ('enviar_email_alerta_cliente_sem_estoque', 'Pode Enviar Email Alerta a Clientes sem Estoque')), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
