# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-08 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_produto_embalagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoquediario',
            name='embalagem',
        ),
        migrations.AlterField(
            model_name='produto',
            name='embalagem',
            field=models.IntegerField(blank=True, default=1, help_text='Quantidade de produtos por embalagem. Exemplo: "10" quer dizer que na embalagem tem 10 pacotes do produto.', null=True),
        ),
    ]
