# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-12 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0024_estoquediario_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoquediario',
            name='cliente',
        ),
    ]
