# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-12 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0026_estoquediario_produto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clienteproduto',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='clienteproduto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='clienteproduto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='estoquediario',
            name='cliente_produto',
        ),
        migrations.DeleteModel(
            name='ClienteProduto',
        ),
    ]
