# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-03-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0027_auto_20190212_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquediario',
            name='erros_importacao',
            field=models.TextField(blank=True, default='', help_text='Erros encontrados ao fazer a importa\xe7\xe3o de estoque de uma planilha.<br/>Os erros podem ser:<br/>1. C\xf3digo de barras com mais de 13 caracteres<br/>2. C\xf3digo de barras com menos de 13 caracteres e diferente do c\xf3digo interno', null=True, verbose_name='Erros na importa\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='estoquediario',
            name='opcao_duplicados',
            field=models.CharField(choices=[(b'1', 'Ignorar os produtos duplicados'), (b'2', 'Somar quantidade dos produtos duplicados'), (b'3', 'Substituir os produtos duplicados')], default='1', help_text='O que o sistema deve fazer quando encontrar um produto que j\xe1 foi importado: "Ignorar", "Somar" ou "Substituir"?', max_length=1, verbose_name='Op\xe7\xe3o produtos duplicados'),
        ),
    ]
