# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-03-06 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0028_auto_20190304_0908'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoquediario',
            unique_together=set([('produto', 'data')]),
        ),
    ]
