# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-03-27 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0029_auto_20190306_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
