# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-03-27 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0032_produto_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoclasse',
            name='cliente',
        ),
    ]
