# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-05-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0035_auto_20190328_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True),
        ),
    ]
