# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-06 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0036_auto_20190520_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
