# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-08-20 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0037_auto_20190606_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquediario',
            name='conferente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoques_do_conferente', to='clientes.Funcionario'),
        ),
    ]
