# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-05 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='config1_horario',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 2, 5, 14, 17, 32, 892904), null=True, verbose_name='Hor\xe1rio'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='config1_ativo',
            field=models.BooleanField(default=True, help_text='Ativa ou destiva o envio desse email de alerta.'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='config1_destinatarios',
            field=models.TextField(blank=True, help_text='Entre com os endere\xe7os de email para o envio do alerta, separados por v\xedrgula. Confira se os emails s\xe3o v\xe1lidos.', null=True, verbose_name='Lista de Destinat\xe1rios'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='config1_titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='T\xedtulo do email'),
        ),
    ]
