# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-06 13:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0015_auto_20190131_1512'),
        ('sistema', '0008_auto_20190205_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('arquivo', models.FileField(upload_to='uploads')),
                ('titulo', models.CharField(max_length=80)),
                ('observacao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_do_cliente', to='clientes.Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_do_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='config1_ativo',
            field=models.BooleanField(default=True, help_text='Ativa ou destiva o envio desse email de alerta.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='config1_horario',
            field=models.TimeField(blank=True, help_text='Defina um hor\xe1rio para que o alerta seja disparado.', null=True, verbose_name='Hor\xe1rio'),
        ),
    ]
