# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-27 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_arquivoimportacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoimportacao',
            name='tipo',
            field=models.CharField(blank=True, choices=[(b'0', 'Invent\xe1rio - Planilha de Estoque do Sistema')], max_length=1, null=True),
        ),
    ]
