# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20190221_0959'),
        ('sistema', '0012_arquivoimportacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoimportacao',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivosimportacao_do_inventario', to='inventario.Inventario'),
        ),
        migrations.AlterField(
            model_name='arquivoimportacao',
            name='arquivo',
            field=models.FileField(upload_to='uploads_importacao'),
        ),
    ]
