# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-27 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_arquivoimportacao_processado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoimportacao',
            name='processado',
            field=models.BooleanField(default=False, help_text='Fica "verdadeiro" quando finaliza o processo de importa\xe7\xe3o dos dados para a base.', verbose_name='Processado'),
        ),
    ]
