# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-03-04 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_auto_20190131_1512'),
        ('sistema', '0015_auto_20190227_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoimportacao',
            name='conferente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_impdiario_do_conferente', to='clientes.Conferente'),
        ),
        migrations.AlterField(
            model_name='arquivoimportacao',
            name='tipo',
            field=models.CharField(blank=True, choices=[(b'0', 'Invent\xe1rio - Planilha de Estoque do Sistema'), (b'1', 'Contagem - Planilha de Estoque Di\xe1rio')], max_length=1, null=True),
        ),
    ]
