# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-03-04 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_auto_20190304_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='importacao_arquivo_ativo',
            field=models.BooleanField(default=False, help_text='Ativa ou destiva a IMPORTA\xc7\xc3O AUTOM\xc1TICA DE ARQUIVOS.', verbose_name='Importa\xe7\xe3o de arquivo'),
        ),
    ]
