# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-18 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='contrato_data',
            new_name='cadastro',
        ),
    ]
