# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-21 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20190118_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, db_index=True, help_text="Exemplo: '75360-000'", max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.ForeignKey(blank=True, help_text='Clique na lupa para selecionar ou digite o c\xf3digo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_da_cidade', to='clientes.Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Entre com um EMAIL v\xe1lido', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, help_text='Rua, Avenida, Pra\xe7a, Bairro, Quadra, Lote, N\xfamero', max_length=100, null=True, verbose_name='Endere\xe7o'),
        ),
    ]
