# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-21 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0005_auto_20190121_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=85, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=25, null=True)),
                ('celular', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, help_text='Entre com um EMAIL v\xe1lido', max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_do_cliente', to='clientes.Cliente')),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='funcionario_do_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
