# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-21 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='funcionario_do_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
