# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-28 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20190122_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferente',
            fields=[
            ],
            options={
                'verbose_name': 'Conferente',
                'proxy': True,
                'verbose_name_plural': 'Conferentes',
            },
            bases=('clientes.funcionario',),
        ),
    ]
