# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-28 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_conferente'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
    ]
