# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_grupocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_do_grupo', to='clientes.GrupoCliente'),
        ),
    ]
