# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-31 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_funcionario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionariofuncao',
            options={'ordering': ('nome',), 'permissions': (('gerenciar_permissoes_acesso', 'Pode Gerenciar Permiss\xf5es de Acesso'),), 'verbose_name': 'Fun\xe7\xe3o', 'verbose_name_plural': 'Fun\xe7\xf5es'},
        ),
    ]
