# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-02 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_localdeposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gondola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('local_deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gondolas_do_local_deposito', to='clientes.LocalDeposito')),
            ],
        ),
    ]
