# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-05 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_auto_20190404_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=28)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Se\xe7\xe3o',
                'verbose_name_plural': 'Se\xe7\xf5es',
            },
        ),
        migrations.AlterModelOptions(
            name='gondola',
            options={'ordering': ('nome',), 'verbose_name': 'G\xf4ndola', 'verbose_name_plural': 'G\xf4ndolas'},
        ),
        migrations.AlterModelOptions(
            name='localdeposito',
            options={'ordering': ('nome',), 'verbose_name': 'Local de Estoque', 'verbose_name_plural': 'Locais de Estoque'},
        ),
        migrations.AddField(
            model_name='secao',
            name='local_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes_do_local_deposito', to='clientes.LocalDeposito'),
        ),
    ]
