# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_auto_20190405_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gondola',
            name='local_deposito',
        ),
        migrations.AddField(
            model_name='gondola',
            name='secao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gondolas_da_secao', to='clientes.Secao'),
        ),
    ]
