# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_auto_20190509_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='quantidade_codigo_barras',
            field=models.PositiveSmallIntegerField(blank=True, default=4, null=True),
        ),
    ]
