# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_cliente_quantidade_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='considerar_quant_codbarras',
            field=models.BooleanField(default=True),
        ),
    ]
