# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_cliente_considerar_quant_codbarras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='considerar_quant_codbarras',
            field=models.BooleanField(default=True, verbose_name='Considerar a quantidade padr\xe3o de caracteres para c\xf3digo de barras?'),
        ),
    ]
