# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_auto_20190618_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='considerar_quant_codbarras',
            field=models.BooleanField(default=False, verbose_name='Considerar a quantidade padr\xe3o de caracteres para c\xf3digo de barras?'),
        ),
    ]
