# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-19 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_auto_20190618_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariofuncao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_do_cliente', to='clientes.Cliente'),
        ),
    ]
